export const obj = {
    wife:{
        name:'Fatima Zahrae 👩‍🍳',
        age: 2002,
        phone:'0675558909',
        job:'Wife Of Developer',
        city: 'Habite a Sale',
        year: 20,
        img: "../photos/fati.jpg",
    },
    sister:{
        name:'Hanane Chentouf 👩‍⚖️',
        age: 1990,
        phone:212090020929,
        job:'Doctora du Farmacie',
        city: 'Habite a Lion a France',
        year: 32,
        img:"../photos/hanane.jpg",
    },
    mother:{
        name:'Maha chentouf 👩‍🦰',
        age: 2009,
        phone:'0622554509',
        job:'Sister Of Developer',
        city: 'Habite a Bouznika',
        year: 13,
        img: "../photos/maha.png",
    },
    bro:{
        name:'Mehdi chentouf 👶',
        age: 2009,
        phone:'0680554509',
        job:'Player of FootBall',
        city: 'Habite a Bouznika',
        year: 13,
        img: "../photos/mehdi.jpg",
    },
    ano:{
        name:'Anass chentouf 🤵🏼',
        age: 1996,
        phone:'0604150882',
        job:'Full-Stack Developer 👨🏼‍💻',
        city: 'Habite a Bouznika',
        year: 26,
        img: "../photos/anas.png",
    },
    sadia:{
        name:'Sadia Esaidi 👵🏼',
        age: 1994,
        phone:'0604159999',
        job:'Mother Of Developer 👨🏼‍💻',
        city: 'Habite a Bouznika',
        year: 28,
        img: "../photos/sadia.png",
    },
}
